-- SQL Server Script
-- Insert Roles (SQL Server uses MERGE instead of INSERT ... ON DUPLICATE KEY)
MERGE INTO roles AS target
USING (VALUES ('USER'), ('MANAGER'), ('ADMIN')) AS source (roleName)
ON target.roleName = source.roleName
WHEN NOT MATCHED THEN
    INSERT (roleName) VALUES (source.roleName);

-- Insert sample Airports (Vietnam)
MERGE INTO airports AS target
USING (VALUES
    ('HAN', N'Sân bay Quốc tế Nội Bài', N'Hà Nội', N'Việt Nam'),
    ('SGN', N'Sân bay Quốc tế Tân Sơn Nhất', N'TP. Hồ Chí Minh', N'Việt Nam'),
    ('DAD', N'Sân bay Quốc tế Đà Nẵng', N'Đà Nẵng', N'Việt Nam'),
    ('CXR', N'Sân bay Quốc tế Cam Ranh', N'Nha Trang', N'Việt Nam'),
    ('HPH', N'Sân bay Cát Bi', N'Hải Phòng', N'Việt Nam'),
    ('PQC', N'Sân bay Quốc tế Phú Quốc', N'Phú Quốc', N'Việt Nam'),
    ('VCA', N'Sân bay Cần Thơ', N'Cần Thơ', N'Việt Nam'),
    ('VII', N'Sân bay Vinh', N'Vinh', N'Việt Nam'),
    ('HUI', N'Sân bay Phú Bài', N'Huế', N'Việt Nam'),
    ('BMV', N'Sân bay Buôn Ma Thuột', N'Buôn Ma Thuột', N'Việt Nam')
) AS source (code, name, city, country)
ON target.code = source.code
WHEN NOT MATCHED THEN
    INSERT (code, name, city, country) 
    VALUES (source.code, source.name, source.city, source.country)
WHEN MATCHED THEN
    UPDATE SET name = source.name, city = source.city, country = source.country;

-- Insert Users with encrypted password (password: admin123, manager123, user123)
-- Note: These are BCrypt hashed passwords generated by the application
-- SQL Server uses GETDATE() instead of NOW()
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@vietnamairlines.com')
BEGIN
    INSERT INTO users (phone, password, full_name, email, roleId, createdAt) 
    VALUES ('0901234567', '$2a$10$XPT8PJ5qzQZYKJKGEoJMZOvN0.YZVJxZ3QqxGj4xGjJYKZxYvLJ3W', N'Quản trị viên', 'admin@vietnamairlines.com', 3, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'manager@vietnamairlines.com')
BEGIN
    INSERT INTO users (phone, password, full_name, email, roleId, createdAt) 
    VALUES ('0902345678', '$2a$10$XPT8PJ5qzQZYKJKGEoJMZOvN0.YZVJxZ3QqxGj4xGjJYKZxYvLJ3W', N'Nguyễn Văn Manager', 'manager@vietnamairlines.com', 2, GETDATE());
END

IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'user@example.com')
BEGIN
    INSERT INTO users (phone, password, full_name, email, roleId, createdAt) 
    VALUES ('0903456789', '$2a$10$XPT8PJ5qzQZYKJKGEoJMZOvN0.YZVJxZ3QqxGj4xGjJYKZxYvLJ3W', N'Trần Thị User', 'user@example.com', 1, GETDATE());
END

-- Insert sample Flights (SQL Server doesn't have INSERT ... ON DUPLICATE KEY)
IF NOT EXISTS (SELECT 1 FROM flights WHERE departure_airport = 'HAN' AND arrival_airport = 'SGN' AND departure_date = '2025-11-10')
BEGIN
    INSERT INTO flights (departure_airport, arrival_airport, departure_time, arrival_time, price, status, departure_date, arrival_date) 
    VALUES
    ('HAN', 'SGN', '2025-11-10 08:00:00', '2025-11-10 10:15:00', 2500000, 'SCHEDULED', '2025-11-10', '2025-11-10'),
    ('SGN', 'HAN', '2025-11-10 14:00:00', '2025-11-10 16:15:00', 2500000, 'SCHEDULED', '2025-11-10', '2025-11-10'),
    ('HAN', 'DAD', '2025-11-11 09:00:00', '2025-11-11 10:30:00', 1800000, 'SCHEDULED', '2025-11-11', '2025-11-11'),
    ('DAD', 'HAN', '2025-11-11 15:00:00', '2025-11-11 16:30:00', 1800000, 'SCHEDULED', '2025-11-11', '2025-11-11'),
    ('SGN', 'PQC', '2025-11-12 07:30:00', '2025-11-12 08:30:00', 1500000, 'SCHEDULED', '2025-11-12', '2025-11-12'),
    ('PQC', 'SGN', '2025-11-12 16:00:00', '2025-11-12 17:00:00', 1500000, 'SCHEDULED', '2025-11-12', '2025-11-12'),
    ('HAN', 'CXR', '2025-11-13 10:00:00', '2025-11-13 12:00:00', 2200000, 'SCHEDULED', '2025-11-13', '2025-11-13'),
    ('CXR', 'HAN', '2025-11-13 18:00:00', '2025-11-13 20:00:00', 2200000, 'SCHEDULED', '2025-11-13', '2025-11-13'),
    ('SGN', 'VCA', '2025-11-14 11:00:00', '2025-11-14 11:50:00', 1200000, 'SCHEDULED', '2025-11-14', '2025-11-14'),
    ('HAN', 'HPH', '2025-11-15 06:00:00', '2025-11-15 06:45:00', 800000, 'SCHEDULED', '2025-11-15', '2025-11-15');
END

-- Insert sample Seats (Economy and Business class seats)
IF NOT EXISTS (SELECT 1 FROM seats)
BEGIN
    INSERT INTO seats (seat_number) VALUES
    -- Economy Class (rows 10-20)
    ('10A'), ('10B'), ('10C'), ('10D'), ('10E'), ('10F'),
    ('11A'), ('11B'), ('11C'), ('11D'), ('11E'), ('11F'),
    ('12A'), ('12B'), ('12C'), ('12D'), ('12E'), ('12F'),
    ('13A'), ('13B'), ('13C'), ('13D'), ('13E'), ('13F'),
    ('14A'), ('14B'), ('14C'), ('14D'), ('14E'), ('14F'),
    ('15A'), ('15B'), ('15C'), ('15D'), ('15E'), ('15F'),
    ('16A'), ('16B'), ('16C'), ('16D'), ('16E'), ('16F'),
    ('17A'), ('17B'), ('17C'), ('17D'), ('17E'), ('17F'),
    ('18A'), ('18B'), ('18C'), ('18D'), ('18E'), ('18F'),
    ('19A'), ('19B'), ('19C'), ('19D'), ('19E'), ('19F'),
    ('20A'), ('20B'), ('20C'), ('20D'), ('20E'), ('20F'),
    -- Business Class (rows 1-5)
    ('1A'), ('1B'), ('1C'), ('1D'),
    ('2A'), ('2B'), ('2C'), ('2D'),
    ('3A'), ('3B'), ('3C'), ('3D'),
    ('4A'), ('4B'), ('4C'), ('4D'),
    ('5A'), ('5B'), ('5C'), ('5D');
END
